image: git.promptus-partners.de:8778/promptus/docker:ruby-2.5.1

rspec:
  before_script:
    - bundle install
    - bundle exec rake db:create
    - bundle exec rake db:schema:load
  variables:
    RAILS_ENV: test
  script:
    - bundle exec rspec
  only:
    - master

rubocop:
  variables:
    RAILS_ENV: test
  before_script:
    - bundle install
  script:
    - bundle exec rubocop -l

deploy_experimental:
  stage: deploy
  script:
    - ANSIBLE_HOST_KEY_CHECKING=false make exp
  environment:
    name: experimental
    url: https://experimental.kemmler.de
  only:
    - master

deploy_staging:
  stage: deploy
  script:
    - ANSIBLE_HOST_KEY_CHECKING=false make staging
  environment:
    name: staging
    url: https://staging.kemmler.de
  only:
    - /^(release|hotfix)\/.+$/
